zuihou:
  redis:
      ip: 192.168.50.53
      port: 6379
      password: ''
  mysql:
    database: zuihou_defaults           # 默认库
    ip: ${MYSQL_IP:192.168.50.53}               # 修改为  数据库IP
    username: root      
    password: lyq522095
    port: 3306
    driverClassName: com.mysql.cj.jdbc.Driver
database:
  multiTenantType: SCHEMA     # 模式
  tenantDatabasePrefix: zuihou_base