zuihou:
  log:
    enabled: false

spring:
  autoconfigure:
    exclude: io.seata.integration.http.HttpAutoConfiguration
  cloud:
    gateway:
      x-forwarded:
        prefixEnabled: false
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: oauth
          uri: lb://zuihou-oauth-server
          predicates:
            - Path=/oauth/**
          filters:
            - StripPrefix=1
        - id: file
          uri: lb://zuihou-file-server
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1
        - id: authority
          uri: lb://zuihou-authority-server
          predicates:
            - Path=/authority/**
          filters:
            - StripPrefix=1
        - id: msgs
          uri: lb://zuihou-msgs-server
          predicates:
            - Path=/msgs/**
          filters:
            - StripPrefix=1
        - id: demo
          uri: lb://zuihou-demo-server
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://zuihou-order-server
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
      default-filters:
        - name: Hystrix
          args:
            name: default
            fallbackUri: 'forward:/fallback'


server:
  port: 8760
  servlet:
    context-path: /api
